Unpin python-openstackclient in test-requirements.txt
...because the alternative is to add pins for one or more of

  * osc-lib
  * os-client-config
  * cliff
  * whatever else...

Also drop the unused OS_* env vars, as they make more-recent
python-openstackclient barf with

   TypeError: __init__() got an unexpected keyword argument 'project_name'

Change-Id: Ibfda43cfc28b5aa6530d4ab3a87a7bc696b9ca7c